wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721849665
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 14
      - 22
      - 23
      - 35
      4: 3.10.14
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
device:
  desc: null
  value: cuda:0
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 100000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1721849683873082026
learning_rate:
  desc: null
  value: 0.000125
tensorboard_log:
  desc: null
  value: None
_last_obs:
  desc: null
  value: "[[[[  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [\
    \  0   0   0 ...   0   0   0]\n   ...\n   [ 76  76  76 ...  77  77  77]\n   [\
    \ 76  76  76 ...  77  77  77]\n   [ 76  76  76 ...  77  77  78]]\n\n  [[  0  \
    \ 0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...\
    \   0   0   0]\n   ...\n   [134 134 134 ... 135 135 135]\n   [134 134 134 ...\
    \ 135 135 135]\n   [134 134 134 ... 135 135 135]]\n\n  [[  0   0   0 ...   0 \
    \  0   0]\n   [  0   0   0 ...   0   0   0]\n   [  0   0   0 ...   0   0   0]\n\
    \   ...\n   [170 170 170 ... 171 171 171]\n   [170 170 170 ... 171 171 171]\n\
    \   [170 170 170 ... 171 171 171]]]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object
    at 0x7a669673f250>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(0, 255, (3, 256, 256), uint8)
action_space:
  desc: null
  value: Box(-0.1, 0.1, (5,), float32)
n_envs:
  desc: null
  value: 1
n_steps:
  desc: null
  value: 5120
gamma:
  desc: null
  value: 0.9
gae_lambda:
  desc: null
  value: 1.0
ent_coef:
  desc: null
  value: 7.5e-08
vf_coef:
  desc: null
  value: 0.95
max_grad_norm:
  desc: null
  value: 0.9
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7a6634be83a0>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function get_schedule_fn.<locals>.<lambda> at 0x7a6767538670>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x7a6695b1f340>
policy:
  desc: null
  value: "ActorCriticCnnPolicy(\n  (features_extractor): NatureCNN(\n    (cnn): Sequential(\n\
    \      (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=50176, out_features=512, bias=True)\n      (1):\
    \ ReLU()\n    )\n  )\n  (pi_features_extractor): NatureCNN(\n    (cnn): Sequential(\n\
    \      (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=50176, out_features=512, bias=True)\n      (1):\
    \ ReLU()\n    )\n  )\n  (vf_features_extractor): NatureCNN(\n    (cnn): Sequential(\n\
    \      (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=50176, out_features=512, bias=True)\n      (1):\
    \ ReLU()\n    )\n  )\n  (mlp_extractor): MlpExtractor(\n    (policy_net): Sequential()\n\
    \    (value_net): Sequential()\n  )\n  (action_net): Linear(in_features=512, out_features=5,\
    \ bias=True)\n  (value_net): Linear(in_features=512, out_features=1, bias=True)\n\
    )"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7a66947015d0>
